### ISSUE TITLE
upstream to rustc

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#105]
Leaving things to do here so they don't get lost

@eddyb in IRC:

> replace the LLVM-generating stuff in trans with lowering miri allocations to LLVM
> it should be more efficient in cases without relocations because you can give LLVM a byte blob
> not sure if its own load-from-constant folding can deal with it

**Comment by oli-obk** [comment]
An open question is how to integrate miri's source into rustc:

* go the `rls` way: integrate the miri repository as a submodule of the rustc repository
* go the `clippy` way: move the miri library into the rustc repository and only develop the miri executable in this repository.

@solson: have you done any work towards moving miri into rustc, or are planning on doing so any time soon? If not, do you mind if I give it a try?

**Comment by solson** [comment]
I haven't done any merging work yet, but I plan to do it relatively soon.

My basic idea was to create a `mir_interp` or `mir::interp` module somewhere (wherever @eddyb suggests) and get the code compiling there. I don't think we should use a submodule.

We'll have to get rid of our dependency on the byteorder crate before merging into rustc.

**Comment by eddyb** [comment]
> `interp`

`interpret`, surely.

**Comment by eddyb** [comment]
> that would limit experimentation in this repo

I have an abstraction layer in mind, so the bulk of the code stays in the compiler and here you keep a driver and extensions to it.

**Comment by eddyb** [comment]
> We'll have to get rid of our dependency on the byteorder crate before merging into rustc.

If you wait a few more days, the old makefiles are getting removed and you can just depend on crates.io.

**Comment by Ericson2314** [comment]
If I make recommend, `git subtree` is nice for preserving history with this sort of thing.

**Comment by eddyb** [comment]
`git subtree` showed up on IRC before, I believe my suggestion was to have a merge commit between two repos (connected by a `git remote`).

Now there's a way to actually make the commits valid in this repo: make a commit to move the files in the right position and roughly the right content, on a miri branch, then merge that branch into Rust.

**Comment by solson** [comment]
There is an integration plan from last week's compiler design sprint [here](https://public.etherpad-mozilla.org/p/rust-compiler-design-sprint-paris-2017-miri).

**Comment by eddyb** [comment]
@brson @alexcrichton Would there be serious issues if we ended up with two roots (commits with no parents) in rust-lang/rust, in order to preserve miri's history? We can do something else otherwise.

**Comment by alexcrichton** [comment]
I don't really understand what the implications of such a situation would be, but I can't think of any reason offhand why that'd be bad

**Comment by solson** [comment]
I just learned from [this blog post](https://www.destroyallsoftware.com/blog/2017/the-biggest-and-weirdest-commits-in-linux-kernel-git-history) that the Linux kernel repo has four initial commits. It doesn't seem like a big deal. One of their roots was even added *by accident*.

**Comment by solson** [comment]
Closing this, since Miri was in fact merged into rustc back in December in https://github.com/rust-lang/rust/pull/45002, and later fully replaced the old const evaluator in https://github.com/rust-lang/rust/pull/46882 just a couple weeks ago. (Thanks @oli-obk and everyone else involved!)
