### ISSUE TITLE
refactor vtables

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#124]
I think it would make sense to store vtables not as allocations but as a

```rust
struct Vtable {
    drop: Option<Pointer>,
    size: u64,
    align: u64,
    methods: Vec<Pointer>,
}
```

# Disadavantages

* This would forbid users from writing their own vtables
* This would forbid users from accessing the vtable as memory

# Advantages

* Stop accessing arbitrary offsets in the vtable depending on which value we want and use struct fields instead
* Give nice error messages when a vtable ptr is mis-used

**Comment by eddyb** [comment]
The only disadvantage I care about: can't use miri to generate the vtables that will be used at runtime.
IMO this is pretty bad because I don't want each backend to duplicate the vtable layout code.

**Comment by oli-obk** [comment]
oh... that makes sense.

Leaving this issue open to add some convenience functions around vtable allocations.
