### ISSUE TITLE
miri doesn't build

### ISSUE THREAD

**Issue by jrmuizel** [solson/miri#158]
It gives the following error:
    Updating git repository `https://github.com/quininer/byteorder.git`
error: failed to load source for a dependency on `byteorder`

Caused by:
  Unable to update https://github.com/quininer/byteorder.git?branch=i128#ef51df29

It looks like the commit ef51df29 no longer exists.

**Comment by oli-obk** [comment]
try running `cargo update`

**Comment by oli-obk** [comment]
Miri compiles again on the latest nightly
