### ISSUE TITLE
Update Cargo.toml because byteorder dependency got deleted from github

### ISSUE THREAD

**Issue by sharazam** [solson/miri#164]
`https://github.com/quininer/byteorder.git` does not exist anymore, but it's in the Cargo.toml.

Build error, of course.

**Comment by sharazam** [comment]
`byteorder = { git = "https://github.com/BurntSushi/byteorder", features = ["i128"]}` seems to compile. Seems like the branch was merged into bytorder master and then the fork got deleted

**Comment by oli-obk** [comment]
fixed in #165
