### ISSUE TITLE
cargo run requires --bin

### ISSUE THREAD

**Issue by stevedonovan** [solson/miri#166]
I had to use `--bin` to specify which executable:
```
cargo run --bin miri tests/run-pass/vecs.rs
```
This is because there's also a cargo-miri exe

**Comment by oli-obk** [comment]
Would be trivial to fix by adding a sub-crate for cargo-miri. Opinions?

**Comment by RalfJung** [comment]
It seems subcrates are not built per default, so the instructions have to change to `cargo build --all`. Also, they are not installed, and there is no `cargo install --all`, so one has to run `cargo install --debug && cargo install --path cargo-miri --debug`...

**Comment by RalfJung** [comment]
FWIW, I pushed "cargo-miri as a subcrate" to <https://github.com/RalfJung/miri/tree/subcrate>. However, due to the reasons stated above (in particular the installation part), I am doubtful whether that's really making things any better.

**Comment by oli-obk** [comment]
I wonder it it would make sense to add a default binary setting to cargo.toml since I've seen this issue show up in a few projects now...

**Comment by RalfJung** [comment]
You mean like this? <https://github.com/rust-lang/cargo/issues/2200>

**Comment by RalfJung** [comment]
This got fixed by using the experimental `default-run` feature.
