### ISSUE TITLE
overflowing-rsh-6.rs fails when run with -O

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#178]
The following fails to fail:
```
cargo run --bin miri -- -O tests/compile-fail/overflowing-rsh-6.rs
```
Is this deliberate? It seems to me that overflows are still a bug, and there's no deep reason miri shouldn't also detect them in release mode. That would just be a matter of not ignoring the return value of `intrinsic_overflowing`.

**Comment by bjorn3** [comment]
unoptimized mir:
```rust
// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
fn main() -> () {
    let mut _0: ();                      // return pointer
    scope 1 {
        let _1: i64;                     // "_n" in scope 1 at <anon>:4:9: 4:11
    }
    let mut _2: (i64, bool);

    bb0: {
        StorageLive(_1);                 // scope 0 at <anon>:4:9: 4:11
        _2 = CheckedShr(const 1i64, const 64i32); // scope 0 at <anon>:4:14: 4:24
        assert(!(_2.1: bool), "attempt to shift right with overflow") -> bb1; // scope 0 at <anon>:4:14: 4:24
    }

    bb1: {
        _1 = (_2.0: i64);                // scope 0 at <anon>:4:14: 4:24
        _0 = ();                         // scope 1 at <anon>:3:11: 5:2
        StorageDead(_1);                 // scope 0 at <anon>:5:2: 5:2
        return;                          // scope 0 at <anon>:5:2: 5:2
    }
}
```

optimized mir:
```rust
// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
fn main() -> () {
    let mut _0: ();                      // return pointer
    scope 1 {
        let _1: i64;                     // "_n" in scope 1 at <anon>:4:9: 4:11
    }

    bb0: {
        StorageLive(_1);                 // scope 0 at <anon>:4:9: 4:11
        _1 = Shr(const 1i64, const 64i32); // scope 0 at <anon>:4:14: 4:24
        _0 = ();                         // scope 1 at <anon>:3:11: 5:2
        StorageDead(_1);                 // scope 0 at <anon>:5:2: 5:2
        return;                          // scope 0 at <anon>:5:2: 5:2
    }
}
```

Rustc emits overflowing Shr in release mode.

**Comment by RalfJung** [comment]
Right. It does that, as far as I understand, because checking for overflow incurs too much of a performance hit. In Miri, that's not the case, we have the information available anyway. So I feel like it'd make sense for miri to catch overflows even if the MIR says they are unchecked. This issue is meant to open the discussion whether others there agree.

(Btw, the `wrapping_add` methods are implemented with an intrinsic, so they would be unaffected by this change.)

**Comment by oli-obk** [comment]
I think we used to error on the operation itself instead of waiting for the assert to trigger. I'd be fine with this change, if a full rustc test suite run doesn't show any regressions. Or we just turn on overflow checks in miri unconditionally. So they are generated in Mir no matter what the user passes

**Comment by RalfJung** [comment]
In the case of unchecked `Shr`, we can know there will never be an assert as the information about whether this overflowed or not is not returned back to the program.

**Comment by eddyb** [comment]
FWIW the reason the assert is explicit in MIR, aside from perhaps optimizing it away in some cases, is that any panicking has to be explicit for the unwinding path to be correct.

The only thing we have to be wary of, although this won't be a problem once miri is upstreamed, is that the wrapping intrinsics should *not* be replaced with the same primitives by MIR optimizations.

**Comment by RalfJung** [comment]
> The only thing we have to be wary of, although this won't be a problem once miri is upstreamed, is that the wrapping intrinsics should not be replaced with the same primitives by MIR optimizations.

Right, that would be a problem if optimizations did that.
