### ISSUE TITLE
Support tests to be run only with MIR-libstd

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#180]
It would be nice if it was possible to mark tests as "requiring MIR-libstd". I've been playing around a little to see which other unsafely implemented data structures miri supports and what is missing if it does not. I have a patch which permits at least *creating* a `HashMap`, if a non-default hasher is chosen (the default hasher uses a syscall to get some random bytes). However, this only works if the MIR in libstd is actually present. I suspect we can quickly run into similar issues with other data structures.

I don't know compiletest well enough; ideally, one could say something like `// require-mir` or so to filter tests. Not sure if that is possible. Also, miri's test suite would have to somehow know whether it is executed with or without MIR in libstd; the easiest way would be for an environment variable to tell it.

(To actually support inserting into a `HashMap`, miri would have to permit a pointer-integer-pointer roundtrip. There are [some ideas](https://github.com/nikomatsakis/rust-memory-model/issues/30) for what that could look like, but in any case that's a whole separate project ;)

**Comment by eddyb** [comment]
pointer-integer-pointer is not that bad if integer is not modified. There are also some operations where you do know what the abstract pointer should look like. The paper @nikomatsakis linked is more relevant to FFI in miri than anything else IMO.

**Comment by RalfJung** [comment]
Oh, but the integer is modified. The HashMap stores something in the least significant bit.

**Comment by eddyb** [comment]
Technically, if it's "under" the requested allocation alignment, bitops can be done on abstract pointers.

**Comment by RalfJung** [comment]
Well but it has to cast to usize before doing bitops, right? So on the miri side, the ptr ends up in the integer allocation and all hope is lost.
I don't see a way to do this much simpler than what the paper suggested, but I am open for ideas :)

**Comment by eddyb** [comment]
> ptr ends up in the integer allocation and all hope is lost.

I designed the miri memory model such that ptr -> int -> ptr is truly a noop. There is no need to throw away the abstract allocation information from the pointer - memory is untyped after all.

**Comment by oli-obk** [comment]
Right now I think doing math on pointers will erase the relocation part. But we can fix that without too much trouble

**Comment by oli-obk** [comment]
Wrt  the topic. I wrote a new system for clippy that doesn't use compiletest, but uses cargo clippy. It can be used for miri, too

**Comment by RalfJung** [comment]
> I wrote a new system for clippy that doesn't use compiletest, but uses cargo clippy. It can be used for miri, too

So does this give us more freedom for specifying our own flags or so? That would make it interesting. Where would I find that system?

You seem to sometimes run miri also against the entire rustc test suite, does that rely on the compiletest stuff?

**Comment by oli-obk** [comment]
Running miri against rustc is a third (and very ad-hoc) system: https://github.com/solson/miri/blob/master/tests/compiletest.rs#L87-L196

The clippy "system" is this short file: https://github.com/Manishearth/rust-clippy/blob/master/tests/examples.rs

Since it reuses cargo instead of reimplementing it, it's very short, even if a few features like filters are missing. I think something along those lines is much cleaner than the huge compiletest code that I get lost in every time I want to do something slightly different than what rustc is doing.

**Comment by RalfJung** [comment]
However, that doesn't give us compile-fail tests with fancy "check the error is in the right line" and so on, does it?

**Comment by oli-obk** [comment]
Most of the time you want ui tests anyhow. The code for figuring out line errors isn't very complex if you remove he suggestions/help/note variants, iirc the plan is to readd them to ui tests, in order to remove compile-fail entirely.

**Comment by RalfJung** [comment]
UI tests? Is that also something we could re-use?

**Comment by oli-obk** [comment]
Only partially.  Ui tests don't cope well with tests printing different but similar things, like some of our tests which produce different stack frame depths.

**Comment by RalfJung** [comment]
I see.
So what do you think the path forward for miri should be?

**Comment by oli-obk** [comment]
Moving compiletest out of tree so we can add features to it that rustc doesn't need.

**Comment by RalfJung** [comment]
@oli-obk implemented this recently.
