### ISSUE TITLE
Run MIR-libstd tests for other architectures

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#202]
Currently, Travis runs MIR-libstd tests only for the host architecture. Ideally, this should also be done for other architectures.

**Comment by oli-obk** [comment]
I think this is blocked on https://github.com/rust-lang/rust/issues/36501, because we can't build apple/windows jemalloc on linux

**Comment by RalfJung** [comment]
Right so we want to build libstd with the system allocator, so the only code that has to be cross-compiled is Rust code.
xargo says that needs something like https://github.com/rust-lang/rust/pull/37975.

**Comment by oli-obk** [comment]
If https://github.com/rust-lang/rust/pull/43628 goes through in its current form, we'd be all set, no more need for xargo

**Comment by RalfJung** [comment]
However, I will soon want for miri to be tested against a libstd that also uses `-Zmir-emit-validate=1`, so this wouldn't really help.

**Comment by oli-obk** [comment]
We can use lld as the linker and we inject our own jemalloc crate which doesn't do anything.

**Comment by oli-obk** [comment]
Or we use features = ["force_alloc_system"] in xargo.toml.

**Comment by RalfJung** [comment]
> Or we use features = ["force_alloc_system"] in xargo.toml.

According to xargo README, that doesn't actually work, exactly due to lack of rust-lang/rust#37975. I did not investigate this further yet.

**Comment by RalfJung** [comment]
Hm, I suppose force_alloc_system is newer. However, just setting that in Xargo does not work:
```
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling gcc v0.3.51
   Compiling libc v0.2.29
   Compiling core v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore)
   Compiling libc v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/rustc/libc_shim)
   Compiling unwind v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libunwind)
   Compiling filetime v0.1.10
   Compiling build_helper v0.1.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/build_helper)
   Compiling compiler_builtins v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/rustc/compiler_builtins_shim)
   Compiling std v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd)
   Compiling cmake v0.1.24
   Compiling rustc_lsan v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/librustc_lsan)
   Compiling rustc_asan v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/librustc_asan)
   Compiling rustc_msan v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/librustc_msan)
   Compiling rustc_tsan v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/librustc_tsan)
   Compiling std_unicode v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd_unicode)
   Compiling rand v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/librand)
   Compiling panic_abort v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libpanic_abort)
   Compiling alloc v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc)
   Compiling panic_unwind v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libpanic_unwind)
   Compiling alloc_system v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc_system)
   Compiling collections v0.0.0 (file:///home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcollections)
error[E0463]: can't find crate for `alloc_jemalloc`

error: aborting due to previous error

error: Could not compile `std`.
```

**Comment by RalfJung** [comment]
I reported this as <https://github.com/rust-lang/rust/issues/43637>. I feel like something fishy is going on...

**Comment by RalfJung** [comment]
The good news is that I locally managed to cross-compile libstd without having a C toolchain for the target! The bad news is that I have no idea how to make that work with the upstream rust-src component... here's what I did:
* Compile rustc stage1 locally (currently you have to also apply <https://github.com/rust-lang/rust/pull/43975> to not fail later).
* Make that stage1 the toolchain we use.
* Patch the rustc source folder: In `$RUSTDIR/src/rustc/compiler_builtins_shim/Cargo.toml`, remove `"c"` from the default features. In `$RUSTDIR/src/libstd/Cargo.toml`, remove `"dylib"` from the crate types.
* In miri's source, `cd xargo`. Edit `Xargo.toml` to remove the `"jemalloc"` feature. (You can remove `"panic_unwind"` as well, it doesn't make a difference.)
* `XARGO_RUST_SRC=$RUSTDIR/src/ RUSTFLAGS='-Zalways-encode-mir -Zmir-emit-validate=1' xargo build --target i686-unknown-linux-gnu` should succeed now!

Unfortunately, it seems cross-compiling a dylib does need a C toolchain for the target, which is why I had to not build libstd as a dylib. It also doesn't seem to be possible to change the crate type depending on features (though maybe build scripts can do something here?), which means there currently is no way to upstream this.

libstd being a dylib really is a huge pain :/

**Comment by RalfJung** [comment]
miri still doesn't run unpatched test cases after this:
```
$ MIRI_SYSROOT=~/.xargo/ cargo run --bin miri -- --target i686-unknown-linux-gnu tests/run-pass-fullmir/heap.rs 
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/miri --target i686-unknown-linux-gnu tests/run-pass-fullmir/heap.rs`
error[E0463]: can't find crate for `alloc_jemalloc`

error: aborting due to previous error
```
This is fixed by adding the following to the test source:
```
#![feature(alloc_system, allocator_api, global_allocator)]
extern crate alloc_system;
#[global_allocator]
static ALLOC: alloc_system::System = alloc_system::System;
```
This *still* fails, but that's because the allocator API emulation in `fn_call.rs` is too tied to particular symbol names.

I don't think there is a way to set the default allocator from outside the source... so even if we managed to get the right libstd, we'd still have to add this silly prelude to every single test.

**Comment by oli-obk** [comment]
> I don't think there is a way to set the default allocator from outside the source... so even if we managed to get the right libstd, we'd still have to add this silly prelude to every single test.

**Comment by oli-obk** [comment]
in the short term we can just add an additional travis matrix for 32 bit

Appveyor already has bot 64 and 32 bit

Macs are blocked on me not having a mac and no mac users being interested enough in miri to get it working with full mir

**Comment by RalfJung** [comment]
> in the short term we can just add an additional travis matrix for 32 bit

Travis seems to only support 64bit :/
We could try using Docker though, maybe?

**Comment by RalfJung** [comment]
The allocator trouble is luckily gone now that the system allocator is the default.

The `compiler_builtin` problem should be solved by https://github.com/rust-lang/rust/pull/56435.

However, that still leaves creating the dylib as a problem: Locally, this works for cross-building from 64bit Linux to 32bit Linux (likely because I have the right gcc toolchain installed), but cross-building to `i686-pc-windows-gnu` fails saying

```
error: linking with `gcc` failed: exit code: 1
  |
  = note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-Wl,--large-address-aware" "/home/r/.xargo/lib/rustlib/i686-pc-windows-gnu/lib/dllcrt2.o" "/home/r/.xargo/lib/rustlib/i686-pc-windows-gnu/lib/rsbegin.o" "-L" "/home/r/.xargo/lib/rustlib/i686-pc-windows-gnu/lib" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.0.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.1.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.10.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.11.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.12.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.13.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.14.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.15.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.2.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.3.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.4.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.5.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.6.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.7.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.8.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.std.7jdjnkt3-cgu.9.rcgu.o" "-o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.dll" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.1uhyejbk9z42l5f3.rcgu.o" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps/std.1pxx9pgyxsed3137.rcgu.o" "-nodefaultlibs" "-L" "/tmp/xargo.oIZd2fSCE80c/target/i686-pc-windows-gnu/release/deps" "-L" "/tmp/xargo.oIZd2fSCE80c/target/release/deps" "-L" "/home/r/.xargo/lib/rustlib/i686-pc-windows-gnu/lib" "-ladvapi32" "-lws2_32" "-luserenv" "-lshell32" "-Wl,-Bstatic" "-Wl,--whole-archive" "/tmp/rustcOs5ByS/libpanic_unwind-68b5125fdea5b3a9.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustcOs5ByS/libunwind-59bf8229558b161a.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustcOs5ByS/liblibc-c2accf2fea9af144.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustcOs5ByS/liballoc-621fa7e1ce74615e.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustcOs5ByS/libcore-79b7f582d7f60a6a.rlib" "-Wl,--no-whole-archive" "/tmp/rustcOs5ByS/libcompiler_builtins-c95cbb7129342495.rlib" "-lgcc_eh" "-lpthread" "-shared" "-Wl,-Bdynamic" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-lmsvcrt" "-luser32" "-lkernel32" "/home/r/.xargo/lib/rustlib/i686-pc-windows-gnu/lib/rsend.o"
  = note: /usr/bin/ld: unrecognized option '--enable-long-section-names'
          /usr/bin/ld: use the --help option for usage information
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `std`.
```

**Comment by RalfJung** [comment]
Cc https://github.com/rust-lang/rust/issues/56443

**Comment by memoryruins** [comment]
https://github.com/rust-embedded/cross utilizes docker on travis and runs tests in QEMU.
Although there are some caveats, it enables testing many more targets.
> cross test is assumed to "work" (test column in the table below) if it can successfully run compiler-builtins test suite.
