### ISSUE TITLE
check all methods on PrimVal for undef correctness

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#213]
Checking anything on the value of the primval must be fallible, because we do not want to expose whether it is undef to the evaluated code.

**Comment by RalfJung** [comment]
The only infallible operations currently seem to be the `from_*` and `is_*`, which seems fine, doesn't it?

**Comment by oli-obk** [comment]
The `is_*` checks could be abused. E.g. if `is_null` were infallible, we might expose the Undef. I just opened the issue so I wouldn't forget about it.

**Comment by oli-obk** [comment]
I went through them. The usages of `is_ptr` and `is_bytes` are fine, since immediately after `to_ptr` and `to_bytes` are called. We just need to be careful around them.
