### ISSUE TITLE
Reallocate/Deallocate is too permissive

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#214]
The following test should fail at the deref, because reallocate could change the address:
```rust
#[feature(heap_api)]

mod std::heal::{allocate, reallocate};
fn main() {
    let x = allocate(1, 1);
    let y = reallocate(1, 1, 1);
    let _ = *x;
}
```

Also, reallocate currently does not validate the `old_size`. This should fail:
```rust
#[feature(heap_api)]

mod std::heal::{allocate, reallocate};
fn main() {
    let x = allocate(1, 1);
    let y = reallocate(2, 1, 1);
}
```
Nor does it validate the alignment. This should fail:
```rust
#[feature(heap_api)]

mod std::heal::{allocate, reallocate};
fn main() {
    let x = allocate(1, 2);
    let y = reallocate(1, 2, 1) as *const u16;
    let _ = *y;
}
```

I was going to do this, but it'll probably conflict with <https://github.com/solson/miri/issues/204#issuecomment-310762968>.

**Comment by RalfJung** [comment]
Oh and same for `deallocate`: It should validate old_size and align.

**Comment by oli-obk** [comment]
Feel free to do this, I'll rebase over your changes.

**Comment by RalfJung** [comment]
All right, putting it on my list. May not happen during the week-end though.
