### ISSUE TITLE
Add ctfe mode

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#217]
There are certain things we do not want (right now) when using miri as a const evaluator.

* comparing pointers
* calling common c functions
* things not explicitly allowed by a rfc
     * local vars
     * array indexing
     * short circuiting
    * match/if/loop/other control flow
    * panic
    * ....

Some of these things can be enabled through rfcs, others might/can never be part of ctfe. For now ctfe mode needs to mirror Rustc's const eval.

**Comment by RalfJung** [comment]
I'd add "comparing dangling pointers to anything" to the list. In #204 you stated that

> We need talk about this, because it will mean that the result of a call to a const fn will differ between calling it at compile time and calling it at runtime even if given the same arguments.

Dangling pointer comparison can be another source of such effects.

EDIT: Ah, never mind. This is actually completely taken care of by not permitting comparing pointers between different allocs.

However, that seems very restrictive. It is possible, at least, to permit comparing in-bounds pointers to different live heap allocs. (And both qualifications are necessary.) Not sure if that's worth it though.

**Comment by oli-obk** [comment]
While it would be possible, all such features need rfcs, because the current const eval doesn't permit it. I marked several locations as "needs rfc" already (There's a new error type in the PR). But that reminds me, I think I'm not forbidding comparing pointers within the same allocation, which we totally need to do for now.

**Comment by RalfJung** [comment]
> I think I'm not forbidding comparing pointers within the same allocation, which we totally need to do for now.

Why that...?

**Comment by oli-obk** [comment]
Just because Rust's const eval doesn't support it right now. We need to dumb down miri artificially until some RFCs go through.

**Comment by RalfJung** [comment]
There is a CTFE mode in master now; what is left to be done to close this issue?

**Comment by oli-obk** [comment]
We need to integrate @eddyb's APFloat implementation for deterministic floats.

We also need to get rid of weak linkage statics in ctfe.

I haven't thought about statics in general yet.

**Comment by eddyb** [comment]
If you're using `ConstFloat` you should have deterministic floats already - although it might be useful to use the `rustc_apfloat` API directly, to keep things clean?

**Comment by oli-obk** [comment]
Well... I'm doing neither right now... We still compute floats on the host

**Comment by eddyb** [comment]
Then I must've misunderstood, my bad.
