### ISSUE TITLE
Miri allows writing to immutable locals and heap allocs

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#219]
The following program is accepted by miri without complaint.

```rust
    let x = 5;
    let y = &x;
    let z = y as *const i32 as *mut i32;
    unsafe {
        *z = 6;
    }
    assert_eq!(x, 6);
```

**Comment by oli-obk** [comment]
cc @RalfJung , @eddyb thinks this could be a simple case of the problems you are trying to solve.

As a first step I implemented a way to "freeze" immutable locals after they have been initialized. Similar to what currently happens for statics. But this is not enough, since I think it is undesired or even UB to do `let x = 5; let z = &x as *const i32 as *mut i32; *z = 6;`, even though no (immutable) borrow exists when the  `*z = 6` statement is evaluated.

I propose track mutability of the pointee in `Pointer` objects and the relocation of `Allocs`. This way we know if a pointer was obtained through nefarious means, even if it was turned into a `usize` somewhere inbetween. What do you think?

**Comment by RalfJung** [comment]
Freezing doesn't work in general though, think of `let x = Cell::new(0);`. `mut` on local variables is essentially just a lint, as far as I am concerned. The real trouble is with the shared borrow `y`, not with the fact that `x` is not marked mutable.

---

I do have a plan for catching reference-related UB in general. It's half-implemented in <https://github.com/RalfJung/miri/tree/mir-validate>. There's hopefully going to be some discussion this week at the all-hands. Then I hope to write up a blog post about this.

**Comment by eddyb** [comment]
@RalfJung I was thinking of a range for a borrow which is also carved up where `UnsafeCell` occurs.

**Comment by oli-obk** [comment]
This is caught by `-Zmir-emit-validate=2`. Can we somehow get level 1 to also catch this?

**Comment by RalfJung** [comment]
It is only caught because it involves a lock violation. If you put in a `Cell`, writes will still not be caught.

However, TBH I don't even see the bug here. As far as I am concerned, the `mut` in bindings is just a lint to prevent accidental writing. It does not have any significance for program behavior, including UB.

**Comment by oli-obk** [comment]
> It does not have any significance for program behavior, including UB.

Oh? well then, one less thing to worry about.

**Comment by RalfJung** [comment]
Well, that's my view. I am not sure if a firm decision by anyone else has been made yet. =)
