### ISSUE TITLE
transmute on `ByValPair` is wrong if field sizes of source and target don't match

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#227]
```rust
    let x: Option<Box<[u8]>> = unsafe {
        let z = std::intrinsics::add_with_overflow(0usize, 0usize);
        std::mem::transmute::<(usize, bool), Option<Box<[u8]>>>(z)
    };
    let y = &x;
```

The allocation pointed to by `y` now contains all zeros, when it should be 9 zeros and 7 undef bytes.

**Comment by RalfJung** [comment]
So essentially this needs do manually emulate padding. :/

Is the gain obtained by having `ByValPair` worth this?

**Comment by eddyb** [comment]
`transmute` should just write to a temporary allocation and read from it.

**Comment by RalfJung** [comment]
Would that essentially amount to always using the `dest_align < src_align` branch?

**Comment by eddyb** [comment]
Sounds about right.

**Comment by oli-obk** [comment]
We can simply add a size check, too. Transmuting a pointer to a usize should not require an alloc.

**Comment by eddyb** [comment]
Less size and more representation. Also known as `(un)pack_if_pair` in `rustc_trans`.

**Comment by oli-obk** [comment]
oh right... that would solve https://github.com/solson/miri/issues/113 immediately, too.

This will get horribly complex fast. Let's do your temporary alloc thing instead.

**Comment by RalfJung** [comment]
Actually, just always using the "slow-pass" that's currently there does not fix the bug -- the allocation remains entirely initialized.
