### ISSUE TITLE
`let x = *Box::new(());` tries to write to integer pointer

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#228]
Our handling of lvalues is wrong. We turn an lvalue pointing to an integer address to a `ByRef` iff one tries to read from the lvalue. That's obviously bad for zsts.

I don't think we should convert an `Lvalue` into a `ByRef` ever. I suggest we create an `Rvalue` type, which is just a thin wrapper around `Lvalue` that forbids writing to it.

The alternative would be to add more special zst code, but I suspect this abuse of `ByRef` as rvalues is going to bite us elsewhere, too. It just feels like an accident waiting to happen.

**Comment by eddyb** [comment]
What's wrong with `ByRef`? `rustc_trans` has a `ByRef` and it... works just fine?

**Comment by RalfJung** [comment]
I cannot reproduce a problem here... no "writing to bad ptr" when I execute this test case:
```rust
fn main() {
    let _ = *Box::new(());
}
```

**Comment by oli-obk** [comment]
Maybe you can't use `_`?

We can use ByRef, but then the pointer inside ByRef needs to be PrimVal

**Comment by RalfJung** [comment]
Indeed I can reproduce the issue with
```rust
fn main() {
    let x = *Box::new(());
    println!("{:?}", x);
}
```
