### ISSUE TITLE
Handle recursive field drop and user-defined destructors

### ISSUE THREAD

**Issue by solson** [solson/miri#25]
It would be best to take advantage of the [`ElaborateDrops`](https://github.com/rust-lang/rust/blob/6b4511755cfe63a46f2db8c72145e07f94911c08/src/librustc_driver/driver.rs#L1054) MIR pass, which is currently run _after_ the `after_analysis` callback that Miri uses.

I'm currently looking into adding a callback between `after_analysis` and `after_trans` for this purpose.

**Comment by solson** [comment]
We already have `ElaborateDrops` in place, but this feature would likely be a lot easier to implement if rustc generated actual `Mir` for drop glue.

**Comment by solson** [comment]
@oli-obk Is enough of this done that we can close this? (due to https://github.com/solson/miri/pull/74)

**Comment by oli-obk** [comment]
Nope, we still have some things not working (like `Option<&T>`, which is a `Layout::RawNullablePointer`. (in fact the tests for the impl for that just finished successfully)

I'm running the rustc run-pass tests now to see if any other cases pop up.

Also I don't think the following works:

```rust
struct Foo;
impl Drop for Foo { .. }

enum Bar {
    A(Box<i32>),
    B(Foo),
}
```
