### ISSUE TITLE
Packed struct access alignment failure

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#250]
[This commit](https://github.com/RalfJung/miri/commit/83e45f95c74c1ce6c1463f46db6b77a13d565f10) yields an alignment error on memory access:
```rust
fn test_unsizing2() {
    #[repr(packed)]
    struct Fat<T: ?Sized> {
        f1: isize,
        f2: &'static str,
        ptr: T
    }

    // x is a fat pointer
    fn foo(x: &Fat<[isize]>) {
        assert_eq!({x.f1}, 5);
        assert_eq!({x.ptr[0]}, 1);
        assert_eq!({x.f2}, "some str");
    }

    let f1 : Fat<[isize; 3]> = Fat { f1: 5, f2: "some str", ptr: [1, 2, 3] };
    foo(&f1);
    let f2 : &Fat<[isize; 3]> = &f1;
    foo(f2);
    let f3: &Fat<[isize]> = f2;
    foo(f3);
    let f4: &Fat<[isize]> = &f1;
    foo(f4);
    let f5: &Fat<[isize]> = &Fat { f1: 5, f2: "some str", ptr: [1, 2, 3] };
    foo(f5);
}
```
`foo(f3)` fails. Not sure what is exactly going on -- the lack of miri-backtraces for these errors makes it hard to tell where they are originating...

**Comment by oli-obk** [comment]
The lack of inner backtraces has annoyed me, too. We should create some macro or function that attaches a backtrace to all errors. The backtrace crate should make that pretty easy.

**Comment by RalfJung** [comment]
I'll make a separate issue for that.

**Comment by RalfJung** [comment]
That code does not even compile any more: packed structs must have their last field either non-dropping or sized, because they need to make a copy to call drop glue. It seems possible that the failures we have seen in miri were caused by that copying not happening yet.

I cannot salvage the test using
```rust
    #[repr(packed)]
    struct Fat<T: Copy+?Sized> {
        f1: isize,
        f2: &'static str,
        ptr: T
    }
```
either because no unsized type is `Copy` (from what I can see).

So, closing because rustc doesn't support this either any more, it seems.
