### ISSUE TITLE
Provide inner (miri) backtraces

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#251]
When miri generates an error, it should be possible to get a backtrace of where the error originated.

I kind of thought we'd need error_chain for that, but @oli-obk suggested we could just use the backtrace crate.

**Comment by oli-obk** [comment]
fun fact: `error_chain` uses the `backtrace` crate

**Comment by eddyb** [comment]
I've used `error_chain` + backtraces in a project and now I want in the compiler. cc @nikomatsakis
