### ISSUE TITLE
Handling of `!`

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#261]
Currently, miri has a special handling for the `!` type in `read_lvalue` in `lvalues.rs`: The program is aborted whenever a `!` lvalue is read from.

This has me wonder: Why `!`? Is there any special handling in rustc around the `!` type to tell LLVM about unreachable code? Why are we not also, e.g., checking that a `bool` is valid (i.e., `0` or `1` and not anything else) and a reference aligned?

**Comment by oli-obk** [comment]
There actually used to be something in Mir, telling us about unreachable code at the exact locations at which we abort on `!`, but it disappeared. We now just replicate the old behaviour

**Comment by eddyb** [comment]
It's a hack because rustc used to emit a coercion which in MIR would generate an `Unreachable` terminator and when this was removed, a miri test broke. I'm not sure there's any point to this TBH.

**Comment by RalfJung** [comment]
@eddyb I would expect there to something in codegen, at least around a function returning `!`, that asserts to LLVM that `!` is uninhabited... is there? Is there any way even for unsafe code to violate that promise?

**Comment by eddyb** [comment]
@RalfJung For functions returning `!`, we both don't have a target block in the MIR terminators that are calls to that function, and the function declaration in LLVM will have a `noreturn` attribute.

**Comment by RalfJung** [comment]
I see. So that would already fail now in miri because it would hit the missing target block.

All right, I guess I will then submit a PR to get rid of this check.
