### ISSUE TITLE
Use functions from rustc to simplify our layout and type operations.

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#271]
https://github.com/rust-lang/rust/blob/ef19bd1a339212f77160f12af6d5d85d8bb36ea4/src/librustc/ty/layout.rs#L2084-L2273

relevant discussion: https://github.com/solson/miri/pull/267#discussion_r128911341

**Comment by oli-obk** [comment]
@eddyb literally the only use of `LayoutCx::new` is https://github.com/rust-lang/rust/blob/e3c8433ebb4a1acf125cae34ebd910869c894ebd/src/librustc_trans/context.rs#L750, which also passes an empty parameter environment. Is it expected to ever be used with anything other than an empty parameter env?

**Comment by eddyb** [comment]
`LayoutCx` is what @nikomatsakis replaced the `LayoutTyper` implementation for `InferCtxt` with, when the `ParamEnv` was moved out. It's a bit pointless now, yes.
You only need `ParamEnv` if you evaluate in generic code, which won't be the case here.

**Comment by oli-obk** [comment]
We do evaluate generic code. Currently we do that by monomorphizing every type with the current frame's instance's substs before we use it.

**Comment by eddyb** [comment]
Yes, that's the same as trans, with *nothing* being polymorphic anymore, which is what I meant.

**Comment by RalfJung** [comment]
This has mostly been done, has it not? What is left to do?

**Comment by RalfJung** [comment]
@oli-obk what is the status of this?

**Comment by oli-obk** [comment]
I think nothing here. the miri engine and codegen could use some dedup though
