### ISSUE TITLE
block merging on passing CI

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#279]
Github has a setting to gate merging on successful CI. Can you activate that @solson ? There's also a flag that we can overwrite this, which would help if everything goes haywire out of some reason.

**Comment by RalfJung** [comment]
In this case we should probably also disable direct pushing to master, if that is possible.

**Comment by oli-obk** [comment]
it is possible

**Comment by solson** [comment]
I just enabled these settings:

![image](https://user-images.githubusercontent.com/26806/29001282-394220d0-7a3a-11e7-9dbc-3a4ea6030862.png)

Seem good?

**Comment by eddyb** [comment]
Yupp, thanks!

**Comment by RalfJung** [comment]
The "require branches to be up to date" will mean we have to manually rebase when there are concurrent PRs going on, doesn't it?

**Comment by oli-obk** [comment]
good question... we'll see how it goes and revisit if necessary.

**Comment by RalfJung** [comment]
I think <https://github.com/solson/miri/pull/295> is currently blocked by this.

**Comment by oli-obk** [comment]
Github's update button makes a merge... should be OK if we use the rebase strategy for merging ( in the dropdown menu of the merge button). That strategy can also be configured as the default in the project settings

**Comment by RalfJung** [comment]
I'm not a fan of rebases.

**Comment by RalfJung** [comment]
IMHO we should either do "the full deal" (with bors/homu and everything), or we leave this open and accept that there is some potential left for master being broken.

**Comment by oli-obk** [comment]
The rebase is automatic by github.

But I have no problem with reverting the "branches must be up to date" setting

**Comment by RalfJung** [comment]
> The rebase is automatic by github.

Yeah I understand. I prefer "true" histories though. Makes it much easier to see later what was actually tested/seen by the developer.

**Comment by RalfJung** [comment]
I should clarify: I think rebase makes sense while a feature branch is developed. But once it's up for review, rebasing it again later distorts the view of what has actually been looked at.

**Comment by RalfJung** [comment]
Actually GitHub's "update branch" button does a merge, not a rebase. So I think I am happy with leaving things as-is and just using that button as necessary. :)

**Comment by RalfJung** [comment]
@solson Could you also make AppVeyor required for PRs to be merged?

(I *know* I will be tempted to ignore Windows otherwise. :P )

**Comment by RalfJung** [comment]
Hm, it seems that we only have one queue on AppVeyor, and it's not very smart about cancelling jobs, so when pushing multiple things to a PR. they all get tested one after the other.

**Comment by oli-obk** [comment]
@solson you can check the `Rolling builds` checkbox so appveyor automatically cancels useless jobs

**Comment by RalfJung** [comment]
I think the current situation is fine, actually.
