### ISSUE TITLE
Compile without serde

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#293]
Can we get rid of the dependency on serde? That would enable using a stage 1 compiler to build miri, which would save me a *lot* of time.

**Comment by RalfJung** [comment]
According to @eddyb, serde is pulled in via `cargo_metadata` for "cargo miri". So I suggest we either make cargo miri a feature or a subcrate. Also see #166.

**Comment by oli-obk** [comment]
if we can make it a feature I'd prefer that.

**Comment by RalfJung** [comment]
Unfortunately using the stage 1 compiler still does not work. It doesn't find librustc.

**Comment by RalfJung** [comment]
Also the test suite needs serde to parse rustc JSON output.

So, this is unlikely to ever work without proc macros.
