### ISSUE TITLE
Find a way to get the normalized unerased type of a local

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#298]
Validation needs to be able to access the fully normalize, non-erased type of a local. Currently (well, with https://github.com/solson/miri/pull/297 merged), we use our own copy of some functions from `rustc/infer/mod.rs`, but they end up replacing `ReVar` with `ReErased` for lack of an alternative. That's enough to make the test suite pass, but probably that's just because our test suite is fairly small and doesn't hit the really interesting case here.

Going one step further, validation should actually be able to assert that it never sees a `ReErased`. Currently, it does see them, and the above is not the only source of `ReErased`. I have yet to figure out where the other `ReErased` come from.

Unfortunately, the compiler currently doesn't have the infrastructure to do region inference in a non-erased way, so this will have to wait until @eddyb did some magic in regionck.

**Comment by RalfJung** [comment]
The other ReErased come from types like this `&ReEarlyBound(0, 'a) [T]]` that end up being `&ReErased [u8]` after normalization.

**Comment by eddyb** [comment]
I did give you a potential that doesn't involve regionck rewriting:
```rust
infcx.resolve_regions_and_report_errors(def_id,
                                        &RegionMaps::new(),
                                        &FreeRegionMap::new());
```
You'd have to do this *just after* `select_all_or_error` and before trying to resolve inference variables in the result (and lift it). I just don't know what dummy value you could use for `def_id`.

**Comment by eddyb** [comment]
Oh wow the context is unused! brb making PR to remove it!!!

**Comment by RalfJung** [comment]
I tried `resolve_regions_and_report_errors`, and calling it works, but I was unable to come up with an example that gets fixed by this. In fact, I hard a hard time even finding an example where we actually get incorrect lifetimes currently (the fact that `ReEarlyBound` turns into `ReErased` makes it really hard to test for this). Here is one:
```rust
trait Id {
    type Out;

    fn id(self) -> Self::Out;

   // fn step2(Self::Out) -> 
}

impl<'a> Id for &'a mut i32 {
    type Out = &'a mut i32;

    fn id(self) -> Self { self }
}

impl<'a> Id for &'a mut u32 {
    type Out = &'a mut u32;

    fn id(self) -> Self { self }
}

fn foo<T>(mut x: T) where for<'a> &'a mut T: Id
{
    let x = &mut x;
    let _y = x.id();
    // Inspecting the trace should show that _y has a type involving a local lifetime, when it gets validated.
    // Unfortunately, there doesn't seem to be a way to actually have a test fail if it does not have the right
    // type.  Currently, this is NOT working correctly; see <https://github.com/solson/miri/issues/298>.
}

fn main() {
    foo(3)
}
```
Unfortunately, this involves HRTB, which do not work correctly even with `resolve_regions_and_report_errors`. The trace shows:
```
TRACE:rustc_miri::interpret::step:   // bb1
TRACE:rustc_miri::interpret::step:   Validate(Acquire, [_4: <&ReScope(Remainder(BlockRemainder { block: NodeId(62), first_statement_index: 0 })) mut T as Id>::Out])
TRACE:rustc_miri::interpret::eval_context:   _4: by ref:
TRACE:rustc_miri::interpret::memory:   Alloc Runtime(2): 00 00 00 00 00 00 00 00 (8 bytes, alignment 8) (stack)
TRACE:rustc_miri::interpret::memory:                     └────(Runtime(1))─────┘ 
TRACE:rustc_miri::interpret::memory:   Alloc Runtime(1): 03 00 00 00 (4 bytes, alignment 4) (stack)
TRACE:rustc_miri::interpret::validation:   Acquire on Local { frame: 1, local: _4 }: &ReErased mut i32
TRACE:rustc_miri::interpret::memory:   Frame 1 acquiring Write lock at MemoryPointer { alloc_id: Runtime(2), offset: 0 }, size 8 for region None
TRACE:rustc_miri::interpret::validation:   Acquire on Ptr { ptr: PtrAndAlign { ptr: Pointer { primval: Ptr(MemoryPointer { alloc_id: Runtime(1), offset: 0 }) }, aligned: true }, extra: None }: i32
TRACE:rustc_miri::interpret::memory:   Frame 1 acquiring Write lock at MemoryPointer { alloc_id: Runtime(1), offset: 0 }, size 4 for region None
```
Notice how the type starts out as `<&ReScope(Remainder(BlockRemainder { block: NodeId(62), first_statement_index: 0 })) mut T as Id>::Out`, but then in the validation method we see `&ReErased mut i32`. The region got lost, and it should be a `ReScope`, so this is just wrong.

However, the test case still passes no matter what I do, because when `_y` goes out of scope it actually calls `drop` which means the locks *do* get released at the right time.

**Comment by RalfJung** [comment]
Actually this does not work. Some testcases fail:
```
error: internal compiler error: src/librustc/infer/region_inference/mod.rs:910: cannot relate region: LUB(ReErased, ReEmpty)
```

**Comment by eddyb** [comment]
> the fact that `ReEarlyBound` turns into `ReErased` makes it really hard to test for this

So. Inside a body, it's **not** `ReEarlyBound`. It's `ReFree`. `ReEarlyBound` would be invalid, or would require some de Bruijn gymnastics to make work in that position.
If *something* erases `ReFree` lifetimes, I don't see why it wouldn't erase `ReScope` at the same time. MIR *building* should definitely **not** erase anything.

**Comment by RalfJung** [comment]
Note to future self: [Here](https://github.com/solson/miri/pull/301/commits/977560ca7416f01df039e06eb10ecff6551bdba5) is the code that does more resolution:
```
        use rustc::hir::def_id::{DefId, CRATE_DEF_INDEX};
        use rustc::middle::region::RegionMaps;
        use rustc::middle::free_region::FreeRegionMap;
[...]
            self_.resolve_regions_and_report_errors(
                DefId::local(CRATE_DEF_INDEX),
                &RegionMaps::new(),
                &FreeRegionMap::new()
            );

            let result = self_.resolve_type_and_region_vars_if_possible(result);
```
However, it doesn't work because region resolution is not happy with some of the regions that occur here.

**Comment by oli-obk** [comment]
> However, it doesn't work because region resolution is not happy with some of the regions that occur here.

Note that back when I wrote some of the function pointer calling code I started erasing all kinds of regions everywhere. Maybe that's where your weird regions are coming from?

**Comment by RalfJung** [comment]
I am trying to avoid calling miri's function for this, precisely because it erases regions everywhere, but maybe I accidentally still call one of them somewhere. Next thing I want to do here is figure out where the `ReErased` are still coming from.

**Comment by oli-obk** [comment]
I think this might be happening inside interpreted function calls. The erasing might have already happened for the `Instance`. Even if you are not calling any of miri's functions, you might be reading a type from something that was created via an erasing function.

**Comment by RalfJung** [comment]
I think you are right -- the frame's substitution already contains erased lifetimes:
```
TRACE:rustc_miri::interpret::step:     Validate(Acquire, [_1: &ReFree(DefId { krate: CrateNum(0), node: DefIndex(5) => issue_26709/8cd878b::{{impl}}[0]::drop[0] }, BrAnon(0)) mut Wrapper<ReEarlyBound(0, 'a), T>])
TRACE:rustc_miri::interpret::validation:     Type after substitution: &ReFree(DefId { krate: CrateNum(0), node: DefIndex(5) => issue_26709/8cd878b::{{impl}}[0]::drop[0] }, BrAnon(0)) mut Wrapper<std::marker::Send + ReErased>
TRACE:rustc_miri::interpret::validation:     Substitution: Slice([ReErased, std::marker::Send + ReErased])
```
Notice how `ReEarlyBound(0, 'a)` becomes `ReErased`. TBH I'd rather keep the `ReEarlyBound` for the purpose of validation; that will at some point even let me determine whether this lifetime is `may_dangle` or not...
I tried to find out where the instance gets erased, but couldn't find the spot.

**Comment by oli-obk** [comment]
Right here: https://github.com/solson/miri/blob/master/src/librustc_mir/interpret/terminator/mod.rs#L100

**Comment by RalfJung** [comment]
That erases the sig, but not the instance (called `fn_def` here).

**Comment by oli-obk** [comment]
right. in the non fn ptr case https://github.com/solson/miri/blob/63c48435030c3f3057aa9da8ffb4be8389896050/src/librustc_mir/interpret/eval_context.rs#L1249 erases the regions before we extract the def_id and subst

and in the fn ptr case it's also `operand_ty` called in the `ReifyFnPointer` arm

**Comment by RalfJung** [comment]
I have pretty much given up on ever achieving this, and instead will implement an aliasing model that does not rely on lifetimes.
