### ISSUE TITLE
Many tests fail with: tried to access a dead local variable

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#303]
Looks like something changed in rustc, and it now emits StorageDead/StorageLive differently.

**Comment by oli-obk** [comment]
I think it's purely related to the `box` keyword. The only related PR I've found is https://github.com/rust-lang/rust/pull/43772

**Comment by RalfJung** [comment]
Should be fixed by next nightly, as https://github.com/rust-lang/rust/pull/43859 fixes the issue.

**Comment by RalfJung** [comment]
Fixed upstream.
