### ISSUE TITLE
get `cargo miri` to work with a full mir libstd

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#338]
currently no matter what sysroot flags I pass, I still get missing MIR errors.

**Comment by eddyb** [comment]
False positives from FFI?

**Comment by oli-obk** [comment]
No, things like `String` methods. It's exactly what I'd expect from using the wrong libstd.

**Comment by dwrensha** [comment]
`RUSTFLAGS="-Z always-encode-mir" xargo miri` works for me

**Comment by RalfJung** [comment]
This is now being tested on CI so I will assume that it works.
