### ISSUE TITLE
Add Appveyor

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#345]
@solson can you enable appveyor on this repository?

I tried to do it, but I can't get it to automatically build anything. I need to trigger it manually. Probably a permission/owner thing

**Comment by solson** [comment]
I've never used appveyor before, but I just went through the sign up thing and triggered a build here. https://ci.appveyor.com/project/solson63299/miri

**Comment by solson** [comment]
I can see that appveyor added a GitHub webhook to the repo so it should trigger automatic builds now.

**Comment by oli-obk** [comment]
Thanks! Works great

**Comment by RalfJung** [comment]
Does AppVeyor have a live-updated batch thingy we could add to the README?

**Comment by oli-obk** [comment]
Jup. You can copy paste it from clippy and change the relevant URL parts
