### ISSUE TITLE
Support floating point types f32 and f64

### ISSUE THREAD

**Issue by gnzlbg** [solson/miri#35]
Support floating point types. Probably have to add both `f32`, and `f64` to `PrimVal`, and handle those everywhere. 

AFAIK Rust floating point arithmetic follows IEEE754. Still, I don't know what happens on architectures that do not fully conform to the spec. Does Rust or LLVM emulate it or not? Probably not. This might turn out to not be a problem in practice (e.g. miri result would still be deterministic "enough of the time"). Once we are the we might want to reconsider that though.

**Comment by solson** [comment]
I merged @oli-obk's host-architecture floats, which I think is fine for now. If we later find that not matching target behaviour is a problem in practice, we can revisit this issue.
