### ISSUE TITLE
`cargo build` fails

### ISSUE THREAD

**Issue by mikeyhew** [solson/miri#356]
Using nightly Rust, updated today.

cargo version: `cargo 0.23.0-nightly (e447ac7e9 2017-09-27)`
rustc version: `rustc 1.22.0-nightly (692b94ae2 2017-10-09)`

Error message:

```
error[E0599]: no method named `to_string` found for type `rustc::hir::map::DefPath` in the current scope
   --> miri/bin/miri.rs:119:54
    |
119 |                             self.1.hir.def_path(did).to_string(self.1)
    |                                                      ^^^^^^^^^
    |
    = note: the method `to_string` exists but the following trait bounds were not satisfied:
            `rustc::hir::map::DefPath : std::string::ToString`

error: aborting due to previous error

error: Could not compile `miri`.
```

**Comment by achudnov** [comment]
I've been having trouble building it as well. From the build history I found that the last build succeeded on rustc nightly-2017-09-29. And, indeed, the current tip of the master builds with that version.

**Comment by oli-obk** [comment]
Miri is being merged into the compiler. It's probably best to wait for that instead of duplicating work

**Comment by achudnov** [comment]
> Miri is being merged into the compiler.

Where is that branch located?

**Comment by eddyb** [comment]
@achudnov https://github.com/rust-lang/rust/pull/45002

**Comment by fschutt** [comment]
@eddyb yeah well, how are we supposed to use miri now that it's merged? `rustc miri` or `cargo miri` or some other way? The PR is cool, but I can't see any way how I can use miri now to compile my binary.

**Comment by oli-obk** [comment]
Sorry. I got behind updating miri. We're essentially in the same position as clippy. There is a specific nightly in which miri works. Atm I'm not sure which one though

**Comment by mikeyhew** [comment]
@oli-obk it would be nice to know which nightly to use... at this point I still haven't been able to build miri

**Comment by RalfJung** [comment]
Seems like https://travis-ci.org/solson/miri/builds/317337049 is the last build that worked, it used versions
```
$ rustc --version
rustc 1.24.0-nightly (77efd6800 2017-12-15)
$ rustup --version
rustup 1.7.0 (813f7b7a8 2017-10-30)
$ cargo --version
cargo 0.25.0-nightly (930f9d949 2017-12-05)
```

rust-lang/rust#45002 has been merged by now, but it seems (well, I read somewhere) that https://github.com/rust-lang/rust/pull/46882 is now blocking getting miri to work again.

**Comment by RalfJung** [comment]
This is fixed by now :)
