### ISSUE TITLE
miri builds binaries

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#357]
## Steps to reproduce:

* `cargo run --bin miri tests/run-pass/zst.rs`
* `ls`

This shows that a binary `zst` was created. That should not happen.

**Comment by RalfJung** [comment]
This is still a problem with current miri.

**Comment by bjorn3** [comment]
That is caused by

https://github.com/solson/miri/blob/d4b98b221ddc74524e3c3824e28126b9965150bc/src/bin/miri.rs#L90-L93

**Comment by RalfJung** [comment]
I wonder why it didn't already that that last year, I think that code didn't change much. Oh well.
