### ISSUE TITLE
Say this was merged into rustc

### ISSUE THREAD

**Issue by tmandry** [solson/miri#362]
It looks like miri was [merged into librustc](https://github.com/rust-lang/rust/pull/45002). Is this repository in use anymore? If not, it should say so in the README.

**Comment by oli-obk** [comment]
Only part of it. This repo is still the full blown interpreter, while rustc just contains the core that is shared with const eval

**Comment by tmandry** [comment]
Ah, okay. Thanks for the clarification. There was a [reddit thread](https://www.reddit.com/r/rust/comments/7ju75d/miri_was_merged_into_rustc/) saying that miri was merged into rustc, hence my confusion. Closing this.
