### ISSUE TITLE
Fix remaining compile-fail tests

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#382]
* [ ] compile-fail/match_char2.rs
* [ ] compile-fail/memleak.rs
* [ ] compile-fail/memleak_rc.rs
* [x] compile-fail/overflowing-rsh-2.rs
* [ ] compile-fail/static_memory_modification.rs

**Comment by RalfJung** [comment]
I am seeing 11 failures, not 5:
```
failures:
    [compile-fail] compile-fail/deallocate-bad-alignment.rs
    [compile-fail] compile-fail/deallocate-bad-size.rs
    [compile-fail] compile-fail/deallocate-twice.rs
    [compile-fail] compile-fail/match_char.rs
    [compile-fail] compile-fail/memleak.rs
    [compile-fail] compile-fail/memleak_rc.rs
    [compile-fail] compile-fail/overflowing-rsh-2.rs
    [compile-fail] compile-fail/reallocate-bad-size.rs
    [compile-fail] compile-fail/reallocate-change-alloc.rs
    [compile-fail] compile-fail/reallocate-dangling.rs
    [compile-fail] compile-fail/static_memory_modification.rs
```

**Comment by RalfJung** [comment]
#395 fixes most of them except for

*   compile-fail/match_char.rs
*   compile-fail/memleak.rs
*   compile-fail/memleak_rc.rs
*   compile-fail/static_memory_modification.rs

@oli-obk Why did we stop complaining about writes to static, and out-of-range char (but not bool)?

**Comment by oli-obk** [comment]
A bunch of refactorings. I'll reintroduce it properly once the sanity check PR is merged

**Comment by RalfJung** [comment]
I opened https://github.com/solson/miri/issues/439 specifically for memory leaks.

**Comment by RalfJung** [comment]
I have allowed myself to change the `char` test in the list; `compile-fail/match_char2.rs` is reasonable to reject in the current state whereas `match_char` requires a proper implementation of an all-value validity check.
