### ISSUE TITLE
drop field of vtable cannot ever be null

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#405]
but miri thinks it can be. We should fix this to be in sync with rustc so that rustc can reuse our code

**Comment by RalfJung** [comment]
Where does miri think that?

**Comment by oli-obk** [comment]
At least in https://github.com/rust-lang/rust/blob/master/src/librustc_mir/interpret/terminator/drop.rs#L60

not sure if there are other places (vtable creation looked fine !?)

**Comment by RalfJung** [comment]
I am still not clear on what concretely you are proposing here.

**Comment by oli-obk** [comment]
Looks like miri does not think this anymore. Should have created a permalink XD

**Comment by RalfJung** [comment]
I assume you linked to https://github.com/rust-lang/rust/blob/64a75ecc8014df45b5b875c5820a0406f41ae7bb/src/librustc_mir/interpret/terminator/drop.rs#L60
