### ISSUE TITLE
AppVeyor permissions

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#432]
@solson Can you look into making @oli-obk and me admins for miri on AppVeyor? Auto-canceling does not work very well so sometimes I have to wait hours to get feedback on a windows-specific test that I cannot run locally.

See https://help.appveyor.com/discussions/questions/569-allow-github-project-collaborator-to-configure-appveyor-project-configuration and https://www.appveyor.com/docs/team-setup/#permissions for (seemingly) documentation on how to do this. (Of course, much more complicated than on Travis which just gives access to all GitHub collaborators...)

**Comment by solson** [comment]
I'm on it!

P.S. Please ping me on IRC in the future - I'm way behind on GitHub notifications and only noticed this because @eddyb pointed me to it. :smile:

**Comment by eddyb** [comment]
Should we maybe move miri to `rust-lang-nursery` instead?
cc @nikomatsakis @nrc @kennytm @Mark-Simulacrum

**Comment by RalfJung** [comment]
Thanks @solson! I think I am in that team now. I still do not seem to have permissions in AppVeyor though, at least I cannot see any changes in the UI.

**Comment by Mark-Simulacrum** [comment]
Moving miri into nursery seems like a good idea, but I also don't know that it would help with this specific issue.

**Comment by nrc** [comment]
> Should we maybe move miri to rust-lang-nursery instead?

+1 on this

**Comment by solson** [comment]
Having trouble making this work with GitHub teams, so I would need the email accounts @RalfJung and @oli-obk have on their AppVeyor accounts to add permissions, I think.

I'm fine with moving to the nursery. Just let me know what needs to be done when we're ready to do so.

**Comment by solson** [comment]
I believe @RalfJung should have permissions on AppVeyor now.

**Comment by RalfJung** [comment]
I got an email saying I have "User" role now. Where should I see stuff like restarting a job? Not sure if the UI is bad or if I just still do not have that button.

**Comment by RalfJung** [comment]
Seems like you have to change the "user" role to make this work: https://help.appveyor.com/discussions/problems/6493-user-permissions-button-to-cancel-build-not-visible

**Comment by RalfJung** [comment]
Turns out that when logging in with my GitHub account, where AppVeyor asks me which "account" I want to use (and lists a bunch of teams), I have to select "solson63299" and not "RalfJung". I do not understand how a service can have such bad UI/UX, but whatever, that seems to have worked :)
