### ISSUE TITLE
Revisit NOP cases for intrinsics

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#433]
`copy`, `copy_nonoverlapping` and `write_bytes` currently accept bad pointers when the size is 0, because libstd relies on this.

I think we should enforce the check, and fix libstd.

**Comment by eddyb** [comment]
This is a point of debate in C, too, isn't it? Do we have something conclusive to rely on, and enforce?

**Comment by RalfJung** [comment]
It's UB in C, but compilers do not dare relying on it in general.

I wrote to llvm-dev last year and was unable to get a definite answer out of them... See [this mailing list thread](https://lists.llvm.org/pipermail/llvm-dev/2017-July/115665.html).
