### ISSUE TITLE
No more unsized places

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#435]
Can we just always unpack when we hit an unsized place, and otherwise completely get rid of `PlaceExtra`? That seems neat.

**Comment by eddyb** [comment]
That seems like it would need *a lot* more special cases? IMO PlaceExtra should just be a Scalar.

**Comment by RalfJung** [comment]
Hm, I like having it more typed than that.

**Comment by eddyb** [comment]
Technically you want `Option<Scalar | ByRef>` for the future non-trivial pointer metadata, I plan to make this change to `rustc_codegen_llvm`.

**Comment by RalfJung** [comment]
@eddyb was right, of course. `PlaceExtra` is a `Scalar` now, and unpacking partially gone again because it didn't really work. For example, some types do not even have a sized equivalent -- there is no type "`str` of length `n`".
