### ISSUE TITLE
Fix memory leaks

### ISSUE THREAD

**Issue by RalfJung** [solson/miri#439]
The leak check is currently disabled because most tests would fail. I looked at that for `run-pass/strings.rs`. The remaining non-static allocations at the end are
```
TRACE 2018-08-20T20:45:40Z: rustc_mir::interpret::memory: Alloc 336:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 (16 bytes, alignment 8) (stack)
TRACE 2018-08-20T20:45:40Z: rustc_mir::interpret::memory:             └────────(303)────────┘ 
TRACE 2018-08-20T20:45:40Z: rustc_mir::interpret::memory: Alloc 610:  00 00 00 00 00 00 00 00 0d 00 00 00 00 00 00 00 (16 bytes, alignment 8) (stack)
TRACE 2018-08-20T20:45:40Z: rustc_mir::interpret::memory:             └────────(308)────────┘ 
TRACE 2018-08-20T20:45:40Z: rustc_mir::interpret::memory: Alloc 621:  00 00 00 00 00 00 00 00 (8 bytes, alignment 8) (stack)
TRACE 2018-08-20T20:45:40Z: rustc_mir::interpret::memory:             └────────(313)────────┘ 
TRACE 2018-08-20T20:45:40Z: rustc_mir::interpret::memory: Alloc 628:  00 00 00 00 00 00 00 00 (8 bytes, alignment 8) (stack)
TRACE 2018-08-20T20:45:40Z: rustc_mir::interpret::memory:             └────────(318)────────┘ 
```
These are all (fat or thin) pointers to strings in static memory.

I traced allocation 336 back to where it was created. That happens in statement
```
_4 = &(promoted[15]: &str)
```

This is while evaluating
```
fn empty() -> &'static str {
    ""
}
```
I am a bit surprised here by the types, it almost looks like `_4` has type `&&str` (it's an `&` applied to an `&str`) but maybe that is just printing being odd?

**Comment by RalfJung** [comment]
Minimal reproducing example:
```rust
fn main() {
    let _ = &0;
}
```
This is definitely related to promotion/statics.

@oli-obk I think miri just marks the statics as `Stack` in `init_static`, and it never does something akin to `mark_static_initialized` like it used to. So they get counted for leaks, and they do not get marked read-only. What would be the best way to fix that?

**Comment by bjorn3** [comment]
> I think miri just marks the statics as Stack in init_static, and it never does something akin to mark_static_initialized like it used to.

I had to do that to make statics referencing to mutable statics work. Making a static readonly requires copying it to the tcx, which is always readonly.

https://github.com/solson/miri/blob/f0070fca1e47c836cd2c13524a37e0781fd76a3d/src/lib.rs#L406-L480
