### ISSUE TITLE
Enhance version to include SHA and date

### ISSUE THREAD

**Issue by shepmaster** [solson/miri#452]
```
$ cargo fmt --version
rustfmt 0.99.4-nightly (1c40881 2018-08-27)

$ cargo clippy --version
clippy 0.0.212 (fdd830f 2018-09-08)

$ cargo miri --version
0.1.0
```

[🎶 One of these things is not like the others... 🎶](https://www.youtube.com/watch?v=ueZ6tvqhk8U)

We are adding tool version information to the playground, but miri's current version is not as useful as rustfmt or clippy. Especially considering that it appears y'all don't change the version number. For my own selfish reasons, I'd love it if you kept the same format as the other tools:

> `miri 0.0.0 (0000000 0000-00-00)`

**Comment by shepmaster** [comment]
The general technique is to run a build script, run `git`, and pass along the information in an environment variable.

- [Example from rustfmt](https://github.com/rust-lang-nursery/rust-clippy/commit/fa11aad92a20aaf64c1ee4f43015fba9b6d24b62)

- [Include git commit hash as string into Rust program](https://stackoverflow.com/a/44407625/155423)

**Comment by RalfJung** [comment]
Hm, looking at https://play.rust-lang.org/right now, the miri version looks different than the others -- unlike what you write, the others have the date first, while miri has the SHA first (as in your examples above). Why is that?

**Comment by shepmaster** [comment]
> while miri has the SHA first (as in your examples above). Why is that?

Because the playground doesn't expect that Miri has any of that information and is grabbing the entire version string (which used to just be `x.x.x`):

```rust
    pub fn miri(&self, req: &MiriRequest) -> Result<MiriResponse> {
        self.write_source_code(&req.code)?;
        let mut command = self.miri_command();

        let output = command.output().map_err(Error::UnableToExecuteCompiler)?;

        Ok(MiriResponse {
            success: output.status.success(),
            stdout: vec_to_str(output.stdout)?,
            stderr: vec_to_str(output.stderr)?,
        })
    }
```

https://github.com/integer32llc/rust-playground/blob/ce8cc8b530db1aed170625e05344daa9cc396a5b/ui/src/sandbox.rs#L208-L219

It needs to be updated to use the same code as the others.

**Comment by RalfJung** [comment]
So you are parsing version strings just to reorder them a bit? Well I guess there's a better reason, but anyway it seems no further action is required on our end then. :)

**Comment by shepmaster** [comment]
> reorder them a bit

Mostly to be able to truncate the SHA, yes.
