### ISSUE TITLE
`cargo miri test` no longer correctly detects tests

### ISSUE THREAD

**Issue by apoelstra** [solson/miri#479]
Since https://github.com/rust-lang/rust/pull/53410 the `#[test]` attribute has become a macro and is not visible in the HIR as an attribute. This means that [the code detecting test cases](https://github.com/solson/miri/blob/master/src/bin/miri.rs#L128-L130) never triggers so any `#[test]`-labeled functions are ignored.

CI passes because the effect of this is that the tests simply aren't run, so of course they don't fail :).

I am investigating the effects of the compiler PR. Empirically it looks like functions that used to have a `test` attribute in the HIR now have a `main` attribute, but I'm not sure if that's happening on purpose and if that's the correct way for us to detect test cases now.

**Comment by apoelstra** [comment]
After running with #482 I see that unit tests in libraries don't have the `main` attribute on them. In fact they have no attributes at all :(

**Comment by RalfJung** [comment]
Somehow the test binary has to work, find the tests, run them. How does it do that?

**Comment by apoelstra** [comment]
It looks like [it looks for the `rustc_test_marker` attribute](https://github.com/rust-lang/rust/pull/53410/files#diff-c42059c5ba36507a6260cf628f8de4b2R436) but for some reason in my debug dumps I didn't see this.Maybe it's on a different item than the function itself or something? Maybe it's lost going from AST -> HIR (doesn't sound plausible). I will investigate.

**Comment by apoelstra** [comment]
The `TestDescAndFn` type is defined here: https://github.com/rust-lang/rust/blob/master/src/libtest/lib.rs#L239-L243

Its second field is an enum, which for ordinary test cases is equal to `TestFn::StaticTestFn(func)`, and we want to run the MIR of `func`. But I don't know how to extract it from any of these data structures without nesting a dozen `if`-statements pulling everything apart.

**Comment by Gankro** [comment]
Can you just disable the btree-breaking check for a bit?

**Comment by RalfJung** [comment]
That would mean disabling Stacked Borrows. One can run with `-Zmiri-disable-validation` to achieve that, but then also miri checks way fewer things than it should check.

I can try disabling it inside the BTree module (there's a whiteliist), but that could fail to work because it means references created by BTree are not properly tracked.
