### ISSUE TITLE
use `StorageLive` and `StorageDead` to allocate/deallocate stack memory

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#49]
I haven't read up on them, but the way they are sprayed around in MIR looks very much like that is how they would work.

**Comment by jonas-schievink** [comment]
Note that rust-lang/rust#38669 might cause issues

**Comment by oli-obk** [comment]
yea I already ran into this but failed to fix it in rustc.

**Comment by oli-obk** [comment]
related: https://github.com/rust-lang/rust/pull/39409

**Comment by RalfJung** [comment]
So @nikomatsakis suggested I work on this as a way to make myself familiar with miri. It seems nobody has started tackling this issue yet, so hopefully there won't be any collisions.

**Comment by oli-obk** [comment]
Great! It's all yours
