### ISSUE TITLE
Debugging help

### ISSUE THREAD

**Issue by hermanventer** [solson/miri#496]
I'd like to use VSCode to step through the sources of Miri and Rustc as a way of getting more familiar with the code.

I'm new to Rust and still a bit at sea with the tool chain. A section in the readme that explains how to use VSCode to debug Miri would be awesome.

**Comment by oli-obk** [comment]
I have never even used vscode to debug normal Rust programs, let alone miri or the compiler. in the few cases that I need a debugger I used gdb to step through. and that works out of the box like any other gdb debugging.

Do you already have a way to debug regular rust programs with vscode?

**Comment by hermanventer** [comment]
I do have a way to debug regular rust programs, but it is early days for me yet. While playing around with the settings of VSCode, I drilled into this example `cargo run -v tests/run-pass/vecs.rs`. The last output from that is: ```Running `target/debug/miri tests/run-pass/vecs.rs```.  If immediately afterwards I run `target/debug/miri tests/run-pass/vecs.rs`, it fails with:
```
dyld: Library not loaded: @rpath/librustc_driver-159fb3307eceb69b.dylib
  Referenced from: /Users/hermanv/projects/miri/target/debug/miri
  Reason: image not found
```
I suspect there is some environmental variable that cargo sets that makes it succeed when it is run via cargo. Any thoughts on what this might be would be very helpful.

**Comment by hermanventer** [comment]
For my setup, this path works: `/Users/hermanv/.multirust/toolchains/nightly-x86_64-apple-darwin/lib`. I can now debug by using the following launch.json with VSCode (and after installing these extensions: https://github.com/rust-lang-nursery/rls-vscode and https://github.com/vadimcn/vscode-lldb).

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug executable 'miri'",
            "cargo": {
                "args": [
                    "build",
                    "--bin=miri",
                    "--package=miri",
                ],
            },
            "args": [
                "tests/run-pass/vecs.rs",
            ],
            "cwd": "${workspaceFolder}",
            "env": {
                "DYLD_LIBRARY_PATH": "/Users/hermanv/.multirust/toolchains/nightly-x86_64-apple-darwin/lib"
            }
        }
    ]
}
```

**Comment by RalfJung** [comment]
TBH I think you are more likely to find help in one of the rustc compiler channels (Zulip, IRC, Discord, or the internals forum). Your issue is likely not specific to miri, and there's few enough people following this issue tracker that I think it unlikely someone will be able to help you.

I for one have never managed to get VSCode to do anything sensible with the rustc sources, let alone miri.
