### ISSUE TITLE
Pointer comparison of live non-heap allocations is suspicious

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#552]
In https://github.com/solson/miri/blob/80a6e739424728d7505587ea6c53c39d6687cb59/src/operator.rs#L151 we compare pointers directly, even if they are from different allocations, as long as both are inbounds of live allocations.

Unfortunately optimizations might bite us:

```rust
&42 as *const u32 == &42 as *const u32
```

can be `true` or `false` depending on how these promoteds get deduplicated. Even for explicit local variables

```rust
let x = 42;
let y = 42;
&x as *const u32 == &y as *const u32
```

an optimizer may merge the two variables if they are guaranteed equal (especially if their types are `Copy`).

So we can essentially only compare live heap allocations, static items and mutable local variables, since these are guaranteed distinct in all models I know.

**Comment by RalfJung** [comment]
This is basically https://github.com/solson/miri/issues/131, right?

**Comment by oli-obk** [comment]
Yes
