### ISSUE TITLE
Box is deallocated before drop impl is run

### ISSUE THREAD

**Issue by plietar** [solson/miri#79]
```rust
struct Foo(Box<u8>);
impl Drop for Foo {
    fn drop(&mut self) {
        *self.0 = 255; // error: dangling pointer dereferenced
    }
}

fn main() {
    drop(Foo(Box::new(0)));
}
```

Boxes are immediately deallocated by the drop terminator, where as drop implementations are pushed to the stack, https://github.com/solson/miri/blob/master/src/interpreter/terminator/mod.rs#L531
I'm not sure how to solve this, other than maybe adding a separate type of frame just to deallocate the box.

**Comment by plietar** [comment]
Similar, but the drop implementation is inside the box
```
struct Foo(u8);
impl Drop for Foo {
    fn drop(&mut self) {
        self.0 = 255; // error: dangling pointer dereferenced
    }
}

fn main() {
    drop(Box::new(Foo(0)));
}
```

**Comment by solson** [comment]
@oli-obk Do you have a fix planned for this?

**Comment by oli-obk** [comment]
It's already fixed in my open pr
